apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django.service.name }}
spec:
  type: {{ .Values.django.service.type }}
  selector:
    app: {{ .Values.django.service.name }}
  ports:
    - port: {{ .Values.django.containerPort }}
      targetPort: {{ .Values.django.containerPort }}
