apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: custom-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: JavierGarAgu/devops-project-v2
      image: pruebas:latest