apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: JavierGarAgu/devops-project-v2
      image: 923714621789.dkr.ecr.eu-north-1.amazonaws.com/my-private-repo:latest
      #pruebas:latest
      #never
      imagePullPolicy: Always