django:
  image:
    repository: myapp-django
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicas: 2
  containerPort: 8000
  service:
    name: django
    type: ClusterIP
  env:
    POSTGRES_DB: final_project
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: postgres
    POSTGRES_PORT: "5432"
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  livenessProbe:
    path: /
    port: 8000
  readinessProbe:
    path: /
    port: 8000

nginx:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  replicas: 2
  containerPort: 80
  service:
    name: nginx
    type: LoadBalancer
    port: 80
  config:
    defaultServerName: localhost
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
