name: Test runner EKS Access

on:
  workflow_dispatch:

jobs:
  test-eks:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name private-eks \
            --region eu-north-1

      - name: Check nodes
        run: kubectl get nodes -o wide

      - name: Check system pods
        run: kubectl get pods -n kube-system

      - name: Create test namespace
        run: kubectl create namespace gha-test || echo "namespace exists"

      - name: Deploy a test pod
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Pod
          metadata:
            name: gha-test-pod
            namespace: gha-test
          spec:
            containers:
            - name: nginx
              image: nginx:1.21
              ports:
              - containerPort: 80
          EOF

      - name: Wait for pod to be ready
        run: kubectl wait --for=condition=Ready pod/gha-test-pod -n gha-test --timeout=120s

      - name: Show test pod status
        run: kubectl get pod gha-test-pod -n gha-test -o wide

      - name: Cleanup test resources
        if: always()
        run: |
          kubectl delete pod gha-test-pod -n gha-test --ignore-not-found
          kubectl delete namespace gha-test --ignore-not-found
