name: test runner rds access

# trigger manually with input options
on:
  workflow_dispatch:
    inputs:
      rds_endpoint:
        description: 'RDS endpoint'
        required: true
        default: ''
      rds_secret_arn:
        description: 'RDS Secret ARN'
        required: true
        default: ''

jobs:
  test-eks:
    runs-on: [self-hosted]

    steps:
      # checkout the repository to the runner (optional)
      - name: checkout repo
        uses: actions/checkout@v4

      # install aws cli v2 if necessary
      - name: install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # configure aws credentials using secrets
      - name: set up aws cli
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # install PostgreSQL client and jq on Amazon Linux
      - name: install PostgreSQL client
        run: |
          sudo dnf update -y
          sudo dnf install -y postgresql15 postgresql15-server postgresql15-contrib jq
          # optionally add psql to PATH if needed
          sudo alternatives --install /usr/bin/psql psql /usr/bin/psql-15 15


      # retrieve RDS master password from Secrets Manager
      - name: get RDS credentials
        id: rds
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id ${{ github.event.inputs.rds_secret_arn }} --query SecretString --output text)
          echo "DB_USER=$(echo $SECRET | jq -r '.username')" >> $GITHUB_ENV
          echo "DB_PASS=$(echo $SECRET | jq -r '.password')" >> $GITHUB_ENV
          echo "DB_HOST=${{ github.event.inputs.rds_endpoint }}" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      # test connection to Postgres
      - name: test Postgres connection
        run: |
          echo "Testing connection to RDS Postgres..."
          PGPASSWORD=$DB_PASS psql -h $DB_HOST -U $DB_USER -p $DB_PORT -d postgres -c "SELECT version();"
