name: test runner connectivity

on:
  workflow_dispatch:

jobs:
  check-vm:
    runs-on: [self-hosted]
    steps:
      - name: Test that runner works
        run: |
          echo "ITS WORKING"
          (cat /etc/os-release 2>/dev/null || cat /etc/system-release 2>/dev/null || uname -a)
